// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace azureauth.Entities
{
    [Table("ProductLookup")]
    public partial class ProductLookup
    {
        [Key]
        public long ProductId { get; set; }
        [Required]
        [StringLength(50)]
        public string ProductName { get; set; }
        public long? AvailableUnits { get; set; }
        public long? SoldUnits { get; set; }
        [Column(TypeName = "money")]
        public decimal? Price { get; set; }
        public long VendorId { get; set; }

 
    }
}