// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace azureauth.Entities
{
    [Table("User")]
    public partial class User
    {
        [Key]
        public long Id { get; set; }
        [Required]
        [StringLength(50)]
        public string FirstName { get; set; }
        [Required]
        [StringLength(50)]
        public string LastName { get; set; }
        [StringLength(50)]
        public string Username { get; set; }
        [StringLength(50)]
        public string Email { get; set; }
        [MaxLength(150)]
        public byte[] PasswordHash { get; set; }
        [MaxLength(150)]
        public byte[] PasswordSalt { get; set; }
        [Required]
        [StringLength(50)]
        public string MobileNo { get; set; }
        [Required]
        [StringLength(50)]
        public string UserType { get; set; }
    }
}