// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace azureauth.Entities
{
    [Table("VehicleLookup")]
    public partial class VehicleLookup
    {
        [Key]
        public long VehicleId { get; set; }
        [Required]
        [StringLength(50)]
        public string VehicleName { get; set; }
        [Required]
        [StringLength(50)]
        public string VehicleType { get; set; }
        [Column(TypeName = "money")]
        public decimal BasePrice { get; set; }
        [Column(TypeName = "money")]
        public decimal? PerDayPrice { get; set; }
        [Column(TypeName = "money")]
        public decimal? PerKmPrice { get; set; }
        [Column(TypeName = "money")]
        public decimal? DriverCharge { get; set; }
        [Required]
        [StringLength(50)]
        public string Availablity { get; set; }
        public long VendorId { get; set; }

    }
}