// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace azureauth.Entities
{
    [Table("Vendor")]
    public partial class Vendor
    {
        public Vendor()
        {
            ProductLookups = new HashSet<ProductLookup>();
            VehicleLookups = new HashSet<VehicleLookup>();
        }

        [Key]
        public long VendorId { get; set; }
        [Required]
        [StringLength(50)]
        public string VendorName { get; set; }
        [StringLength(50)]
        public string MoblieContact { get; set; }
        [StringLength(50)]
        public string TelephoneContact { get; set; }
        [StringLength(450)]
        public string Address { get; set; }
        [StringLength(50)]
        public string ServiceType { get; set; }

        public virtual ICollection<ProductLookup> ProductLookups { get; set; }
        public virtual ICollection<VehicleLookup> VehicleLookups { get; set; }
    }
}